### ISSUE TITLE
Registry-console, Metrics and logging not working

### ISSUE THREAD

**Issue by hirenvadalia** [gshipley/installcentos#47]
Thanks for this repo.

I tried to follow this repo (and video mentioned in README) and My installation went successful and I am able to login to openshift web console but when I looked in registry-console, metrics and logging, all them are failed to start.
## Installation logs:
```
INSTALLER STATUS *******************************************************************************************************
Initialization             : Complete (0:00:25)
Health Check               : Complete (0:00:02)
etcd Install               : Complete (0:01:17)
Master Install             : Complete (0:03:25)
Master Additional Install  : Complete (0:00:53)
Node Install               : Complete (0:02:46)
Hosted Install             : Complete (0:01:38)
Web Console Install        : Complete (0:00:29)
Metrics Install            : Complete (0:02:53)
Logging Install            : Complete (0:04:34)
Service Catalog Install    : Complete (0:01:57)

Adding password for user root
cluster role "cluster-admin" added: "root"
******
* Your console is https://console.192.168.31.135.nip.io:8443
* Your username is root
* Your password is password
*
* Login using:
*
$ oc login -u root -p password https://console.192.168.31.135.nip.io:8443/
******
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-service-catalog
    kube-system
    logging
    management-infra
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker
    openshift-web-console

Using project "default".

``` 
## oc status -v
```
In project default on server https://console.192.168.31.135.nip.io:8443

https://docker-registry-default.apps.192.168.31.135.nip.io (passthrough) (svc/docker-registry)
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v3.9.0
    deployment #1 deployed 28 minutes ago - 1 pod

svc/kubernetes - 172.30.0.1 ports 443->8443, 53->8053, 53->8053

https://registry-console-default.apps.192.168.31.135.nip.io (passthrough) (svc/registry-console)
  dc/registry-console deploys docker.io/cockpit/kubernetes:latest
    deployment #1 failed 28 minutes ago: config change

svc/router - 172.30.33.136 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:v3.9.0
    deployment #1 deployed 29 minutes ago - 1 pod

Info:
  * pod/registry-console-1-deploy has no liveness probe to verify pods are still running.
    try: oc set probe pod/registry-console-1-deploy --liveness ...

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```
## oc adm diagnostics
[oc_adm_diagnostics.txt](https://github.com/gshipley/installcentos/files/1991515/oc_adm_diagnostics.txt)

## oc get all --all-namespaces
```
NAMESPACE                           NAME                    DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                         AGE
kube-service-catalog                ds/apiserver            1         1         1         1            1           node-role.kubernetes.io/master=true   33m
kube-service-catalog                ds/controller-manager   1         1         1         1            1           node-role.kubernetes.io/master=true   32m
logging                             ds/logging-fluentd      1         1         1         1            1           logging-infra-fluentd=true            34m
openshift-template-service-broker   ds/apiserver            1         1         1         1            1           region=infra                          32m

NAMESPACE               NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
openshift-web-console   deploy/webconsole   1         1         1            1           41m

NAMESPACE               NAME                       DESIRED   CURRENT   READY     AGE
openshift-web-console   rs/webconsole-84466b9d97   1         1         1         41m

NAMESPACE                              NAME                                                REVISION   DESIRED   CURRENT   TRIGGERED BY
default                                deploymentconfigs/docker-registry                   1          1         1         config
default                                deploymentconfigs/registry-console                  1          1         0         config
default                                deploymentconfigs/router                            1          1         1         config
logging                                deploymentconfigs/logging-curator                   1          1         1         config
logging                                deploymentconfigs/logging-es-data-master-nck7hzw3   1          1         0       
logging                                deploymentconfigs/logging-kibana                    1          1         0         config
openshift-diagnostic-appcreate-6cgjp   deploymentconfigs/diagnostic-appcreate              1          0         1         config

NAMESPACE   NAME                            DOCKER REPO                                                 TAGS                          UPDATED
default     imagestreams/registry-console   docker-registry.default.svc:5000/default/registry-console   latest                        42 minutes ago
openshift   imagestreams/dotnet             docker-registry.default.svc:5000/openshift/dotnet           2.0,latest                    About an hour ago
openshift   imagestreams/dotnet-runtime     docker-registry.default.svc:5000/openshift/dotnet-runtime   2.0,latest                    About an hour ago
openshift   imagestreams/httpd              docker-registry.default.svc:5000/openshift/httpd            latest,2.4                    About an hour ago
openshift   imagestreams/jenkins            docker-registry.default.svc:5000/openshift/jenkins          1,2,latest                    About an hour ago
openshift   imagestreams/mariadb            docker-registry.default.svc:5000/openshift/mariadb          10.1,10.2,latest              About an hour ago
openshift   imagestreams/mongodb            docker-registry.default.svc:5000/openshift/mongodb          2.4,2.6,3.2 + 2 more...       About an hour ago
openshift   imagestreams/mysql              docker-registry.default.svc:5000/openshift/mysql            5.5,5.6,5.7 + 1 more...       About an hour ago
openshift   imagestreams/nginx              docker-registry.default.svc:5000/openshift/nginx            1.12,1.8,latest + 1 more...   About an hour ago
openshift   imagestreams/nodejs             docker-registry.default.svc:5000/openshift/nodejs           0.10,4,6 + 2 more...          About an hour ago
openshift   imagestreams/perl               docker-registry.default.svc:5000/openshift/perl             5.16,5.20,5.24 + 1 more...    About an hour ago
openshift   imagestreams/php                docker-registry.default.svc:5000/openshift/php              7.1,latest,5.5 + 2 more...    About an hour ago
openshift   imagestreams/postgresql         docker-registry.default.svc:5000/openshift/postgresql       9.2,9.4,9.5 + 2 more...       About an hour ago
openshift   imagestreams/python             docker-registry.default.svc:5000/openshift/python           3.3,3.4,3.5 + 3 more...       About an hour ago
openshift   imagestreams/redis              docker-registry.default.svc:5000/openshift/redis            latest,3.2                    About an hour ago
openshift   imagestreams/ruby               docker-registry.default.svc:5000/openshift/ruby             2.0,2.2,2.3 + 2 more...       About an hour ago
openshift   imagestreams/wildfly            docker-registry.default.svc:5000/openshift/wildfly          10.1,8.1,9.0 + 2 more...      About an hour ago

NAMESPACE              NAME                      HOST/PORT                                                   PATH      SERVICES           PORT      TERMINATION          WILDCARD
default                routes/docker-registry    docker-registry-default.apps.192.168.31.135.nip.io                    docker-registry    <all>     passthrough          None
default                routes/registry-console   registry-console-default.apps.192.168.31.135.nip.io                   registry-console   <all>     passthrough          None
kube-service-catalog   routes/apiserver          apiserver-kube-service-catalog.apps.192.168.31.135.nip.io             apiserver          secure    passthrough          None
logging                routes/logging-kibana     kibana.apps.192.168.31.135.nip.io                                     logging-kibana     <all>     reencrypt/Redirect   None
openshift-infra        routes/hawkular-metrics   hawkular-metrics.apps.192.168.31.135.nip.io                           hawkular-metrics   <all>     reencrypt            None

NAMESPACE                              NAME                                          READY     STATUS             RESTARTS   AGE
default                                po/docker-registry-1-6ng6b                    1/1       Running            0          42m
default                                po/registry-console-1-deploy                  0/1       Error              0          42m
default                                po/router-1-bc68m                             1/1       Running            0          43m
kube-service-catalog                   po/apiserver-6kzm6                            1/1       Running            0          33m
kube-service-catalog                   po/controller-manager-hdkbj                   1/1       Running            0          32m
logging                                po/logging-curator-1-g62b5                    1/1       Running            7          35m
logging                                po/logging-es-data-master-nck7hzw3-1-deploy   0/1       Error              0          34m
logging                                po/logging-fluentd-b9b6k                      1/1       Running            0          34m
logging                                po/logging-kibana-1-deploy                    0/1       Error              0          35m
openshift-diagnostic-appcreate-6cgjp   po/diagnostic-appcreate-1-vj6xn               1/1       Running            0          4m
openshift-infra                        po/hawkular-cassandra-1-f98nf                 0/1       CrashLoopBackOff   11         39m
openshift-infra                        po/hawkular-metrics-s8jln                     0/1       CrashLoopBackOff   14         39m
openshift-infra                        po/heapster-c4kdn                             0/1       Running            4          38m
openshift-template-service-broker      po/apiserver-2zqfs                            1/1       Running            0          32m
openshift-web-console                  po/webconsole-84466b9d97-c5rzb                1/1       Running            2          41m

NAMESPACE                              NAME                                   DESIRED   CURRENT   READY     AGE
default                                rc/docker-registry-1                   1         1         1         42m
default                                rc/registry-console-1                  0         0         0         42m
default                                rc/router-1                            1         1         1         43m
logging                                rc/logging-curator-1                   1         1         1         35m
logging                                rc/logging-es-data-master-nck7hzw3-1   0         0         0         34m
logging                                rc/logging-kibana-1                    0         0         0         35m
openshift-diagnostic-appcreate-6cgjp   rc/diagnostic-appcreate-1              1         1         1         4m
openshift-infra                        rc/hawkular-cassandra-1                1         1         0         39m
openshift-infra                        rc/hawkular-metrics                    1         1         0         39m
openshift-infra                        rc/heapster                            1         1         0         39m

NAMESPACE                           NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
default                             svc/docker-registry            ClusterIP   172.30.33.55     <none>        5000/TCP                              43m
default                             svc/kubernetes                 ClusterIP   172.30.0.1       <none>        443/TCP,53/UDP,53/TCP                 48m
default                             svc/registry-console           ClusterIP   172.30.164.99    <none>        9000/TCP                              42m
default                             svc/router                     ClusterIP   172.30.33.136    <none>        80/TCP,443/TCP,1936/TCP               43m
kube-service-catalog                svc/apiserver                  ClusterIP   172.30.111.155   <none>        443/TCP                               33m
logging                             svc/logging-es                 ClusterIP   172.30.29.28     <none>        9200/TCP                              36m
logging                             svc/logging-es-cluster         ClusterIP   172.30.207.66    <none>        9300/TCP                              36m
logging                             svc/logging-es-prometheus      ClusterIP   172.30.8.32      <none>        443/TCP                               36m
logging                             svc/logging-kibana             ClusterIP   172.30.54.197    <none>        443/TCP                               36m
openshift-infra                     svc/hawkular-cassandra         ClusterIP   172.30.180.60    <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   40m
openshift-infra                     svc/hawkular-cassandra-nodes   ClusterIP   None             <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   40m
openshift-infra                     svc/hawkular-metrics           ClusterIP   172.30.187.119   <none>        443/TCP                               40m
openshift-infra                     svc/heapster                   ClusterIP   172.30.163.27    <none>        80/TCP                                39m
openshift-template-service-broker   svc/apiserver                  ClusterIP   172.30.255.151   <none>        443/TCP                               32m
openshift-web-console               svc/webconsole                 ClusterIP   172.30.207.143   <none>        443/TCP                               41m
```

**Comment by hirenvadalia** [comment]
@ryannix123 Yes I have 16 GB of RAM and 16 cores (8 cpus with 2 cores on each)

**Comment by ryannix123** [comment]
Strange. I have half that amount if RAM and those components have never failed to deploy.

**Comment by ryannix123** [comment]
I've only used Bridged networking. That could be the issue, although I'm not certain.

**Comment by hirenvadalia** [comment]
Ok I can give try using bridge networking... But does openshift have any limitations on NAT networking?

**Comment by hirenvadalia** [comment]
@ryannix123 So tried with bridge networking and results is same... registry-console, metrics and logging is still fail to start...
I also looking in pods logs but I have no idea about whatever error it shows:

## oc logs po/registry-console-1-9k668
```
2018/05/10 15:59:33 Failed to generate certificates exit status 1 remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: TLS support is not available
```

## oc logs po/hawkular-cassandra-1-78bl8 -n openshift-infra
```
The MAX_HEAP_SIZE envar is not set. Basing the MAX_HEAP_SIZE on the available memory limit for the pod (2000000000).
The memory limit is less than 2GB. Using 1/2 of available memory for the max_heap_size.
The MAX_HEAP_SIZE has been set to 953M
The HEAP_NEWSIZE envar is not set. Setting the HEAP_NEWSIZE to one third the MAX_HEAP_SIZE: 317M
About to generate seeds
Trying to access the Seed list [try #1]
Trying to access the Seed list [try #2]
Trying to access the Seed list [try #3]
Setting seeds to be hawkular-cassandra-1-78bl8
Creating the Cassandra keystore from the Secret's cert data
Converting the PKCS12 keystore into a Java Keystore
keytool error: java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:792)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1998)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at sun.security.tools.keytool.Main.loadSourceKeyStore(Main.java:1901)
        at sun.security.tools.keytool.Main.doImportKeyStore(Main.java:1939)
        at sun.security.tools.keytool.Main.doCommands(Main.java:1028)
        at sun.security.tools.keytool.Main.run(Main.java:345)
        at sun.security.tools.keytool.Main.main(Main.java:338)
Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.Security.getImpl(Security.java:695)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:786)
        ... 7 more
Failed to create a Java Keystore file with the service-specific certificate. Aborting.
```

## oc logs po/hawkular-metrics-mxttm -n openshift-infra
```
2018-05-10 16:05:29 Starting Hawkular Metrics
unable to write 'random state'
unable to write 'random state'
The service account has read permissions for its project. Proceeding
The service account has permission to watch namespaces. Proceeding
Creating the Hawkular Metrics keystore from the Secret's cert data
unable to write 'random state'
Converting the PKCS12 keystore into a Java Keystore
keytool error: java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:792)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1998)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at sun.security.tools.keytool.Main.loadSourceKeyStore(Main.java:1901)
        at sun.security.tools.keytool.Main.doImportKeyStore(Main.java:1939)
        at sun.security.tools.keytool.Main.doCommands(Main.java:1028)
        at sun.security.tools.keytool.Main.run(Main.java:345)
        at sun.security.tools.keytool.Main.main(Main.java:338)
Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.Security.getImpl(Security.java:695)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:786)
        ... 7 more
Failed to create a Java Keystore file with the service-specific certificate. Aborting.
```

## oc logs po/logging-kibana-1-deploy -n logging
```
--> Scaling logging-kibana-1 to 1
error: update acceptor rejected logging-kibana-1: watch closed before Until timeout
--> Error listing events for replication controller logging-kibana-1: Get https://172.30.0.1:443/api/v1/namespaces/logging/events?fieldSelector=involvedObject.name%3Dlogging-kibana-1%2CinvolvedObject.namespace%3Dlogging%2CinvolvedObject.kind%3DReplicationController%2CinvolvedObject.uid%3D7341117d-546b-11e8-a515-000c29fa4f6f: dial tcp 172.30.0.1:443: getsockopt: connection refused
```
## oc logs po/logging-es-data-master-z2sbetye-1-deploy -n logging
```
--> Scaling logging-es-data-master-z2sbetye-1 to 1
error: update acceptor rejected logging-es-data-master-z2sbetye-1: watch closed before Until timeout
--> Error listing events for replication controller logging-es-data-master-z2sbetye-1: Get https://172.30.0.1:443/api/v1/namespaces/logging/events?fieldSelector=involvedObject.name%3Dlogging-es-data-master-z2sbetye-1%2CinvolvedObject.namespace%3Dlogging%2CinvolvedObject.kind%3DReplicationController%2CinvolvedObject.uid%3Da2a84609-546b-11e8-a515-000c29fa4f6f: dial tcp 172.30.0.1:443: getsockopt: connection refused
```

## oc logs po/registry-console-1-deploy
```
--> Scaling registry-console-1 to 1
--> Error listing events for replication controller registry-console-1: Get https://172.30.0.1:443/api/v1/namespaces/default/events?fieldSelector=involvedObject.name%3Dregistry-console-1%2CinvolvedObject.namespace%3Ddefault%2CinvolvedObject.kind%3DReplicationController%2CinvolvedObject.uid%3D9f48d9e8-546a-11e8-a515-000c29fa4f6f: dial tcp 172.30.0.1:443: getsockopt: connection refused
error: update acceptor rejected registry-console-1: watch closed before Until timeout
```

**Comment by hirenvadalia** [comment]
@ryannix123 any update on this? Sorry for pushing this but I really stucked on this...

**Comment by ryannix123** [comment]
Do you have ports 80,443, and 8443 open to the world?

**Comment by hirenvadalia** [comment]
@ryannix123 Sorry I didn't get you... I am doing this installation in my VM and that VM is only accessible from my host machine... But I can access all above ports from my host machine.
Do I need to setup/configure anything extra, apart from what install-openshift.sh does?

**Comment by ryannix123** [comment]
In my experience, the ports I listed have to be open to the world before a successful install can take place.

**Comment by hirenvadalia** [comment]
Means I have to add those ports in my router's port forwarding? like @gshipley shown in video?

**Comment by ryannix123** [comment]
Correct. Please try that.

**Comment by hirenvadalia** [comment]
Alright... let me try that...
BTW Thanks a lot for quick help, really appropriated

**Comment by hirenvadalia** [comment]
@ryannix123 Sorry but I can't test with opening ports to world as my network provider doesn't allow that unless I buy static IP, which I don't want to.
So now I can open ports in my internal network only.

BTW why I need to open my openshift setup to world? I don't want to expose my openshift setup to world, as that setup is only for me.

is it possible for you to try without opening those ports to world and see whether you are able to success in installing openshift correctly?

**Comment by hirenvadalia** [comment]
@ryannix123 Just update on this: I tried installing openshift v3.7.1 (from commit 26215424) (With replacing 'docker-1.12-6' with 'docker' in install-openshift.sh as docker-1.12.6 is no more available in CentOS 7 by default)
And I got everything up and running including registry-console, metrics and logging...
And I have not exposed any of ports in my router configuration... + I am using NAT networking...
So I guess openshift doesn't have any requirement of exposing ports or using Bridge networking...

Now I have very strong feeling that there is something wrong in release-3.9 branch in openshift-ansible repo, which is restricting successful deployment of registry-console, metrics and logging

**Comment by hirenvadalia** [comment]
Looks like today is my lucky day... I tried installing OpenShift v3.9 in same machine (in which OpenShift v3.7.1 installed successfully) and it passed, everything is up and running...

So looks like some problem in my older VM... may I messed up while setting fqdn and domain...

Closing this issue as it is not valid anymore....
